baseURL = "https://johndec.github.io"
languageCode = "en-us"
title = "callosum"
paginate = 8
theme = "m10c"

[params]
  author = "John D. DeCuir"
  description = "Verba volant, scripta manent"

  [[params.social]]
    icon = "github"
    name = "My Github"
    url = "https://github.com/johndec"
  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/decuir/"

[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#ffffff"